apiVersion: v1
kind: Service
metadata:
  name: default-backend-redirect
  namespace: ingress-nginx
spec:
  selector:
    app: default-backend-redirect
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend-redirect
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-backend-redirect
  template:
    metadata:
      labels:
        app: default-backend-redirect
    spec:
      containers:
      - name: redirect
        image: nginx:alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: redirect-nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redirect-nginx-config
  namespace: ingress-nginx
data:
  default.conf: |
    server {
      listen 8080;
      location / {
        return 302 https://www.google.com;
      }
    }

