apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "4.11.7"
  values:
    defaultBackend:
      enabled: false
    controller:
      service:
        type: LoadBalancer
      defaultBackendService: ingress-nginx/default-backend-redirect
      extraVolumes:
      - name: lua-plugins
        configMap:
          name: lua-redirect-plugin
      extraVolumeMounts:
      - name: lua-plugins
        mountPath: /etc/nginx/lua/plugins
      config: {}

