apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "4.11.7"
  values:
    defaultBackend:
      enabled: false
    controller:
      service:
        type: LoadBalancer
      defaultBackendService: ingress-nginx/default-backend-redirect
      extraVolumes:
      - name: lua-plugins
        configMap:
          name: lua-redirect-plugin
      extraVolumeMounts:
      - name: lua-plugins
        mountPath: /etc/nginx/lua/plugins
      config:
        http-snippet: |
          init_by_lua_block {
            -- Store original header function
            local original_header = nil
            _G.handle_404_redirect = function()
              local status = ngx.status
              if status == 404 then
                ngx.status = 302
                ngx.header["Location"] = "https://www.google.com"
                ngx.header["Content-Type"] = "text/html"
                ngx.header.content_length = nil
              end
            end
          }
        server-snippet: |
          # Use error_page to catch 404s and redirect
          error_page 404 = @redirect_404;
          location @redirect_404 {
            return 302 https://www.google.com;
          }

