apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "4.11.7"
  values:
    controller:
      service:
        type: LoadBalancer
      config:
        server-snippet: |
          error_page 404 = @redirect_404;
          location @redirect_404 {
            rewrite_by_lua_block {
              ngx.redirect("https://www.google.com", 302)
            }
          }
        http-snippet: |
          header_filter_by_lua_block {
            if ngx.status == 404 then
              ngx.header["Location"] = "https://www.google.com"
              ngx.status = 302
              ngx.header.content_length = nil
              ngx.header.content_type = nil
            end
          }
          body_filter_by_lua_block {
            if ngx.status == 302 and ngx.header["Location"] == "https://www.google.com" then
              ngx.arg[1] = ""
              ngx.arg[2] = true
            end
          }

