apiVersion: v1
kind: ConfigMap
metadata:
  name: lua-redirect-plugin
  namespace: ingress-nginx
data:
  redirect-404.lua: |
    local plugin_name = "redirect-404"
    
    local _M = {
      version = "0.1",
      priority = 1000,
      name = plugin_name,
    }
    
    function _M.header_filter()
      if ngx.status == 404 then
        ngx.header["Location"] = "https://www.google.com"
        ngx.status = 302
        ngx.header.content_length = nil
        ngx.header.content_type = nil
      end
    end
    
    function _M.body_filter()
      if ngx.status == 302 and ngx.header["Location"] == "https://www.google.com" then
        ngx.arg[1] = ""
        ngx.arg[2] = true
      end
    end
    
    return _M

