apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "6.0.0"
  values:
    deploymentMode: SingleBinary
    simpleScalable:
      replicas: 0
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      storage_config:
        filesystem:
          directory: /loki/chunks
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 20Gi
        storageClassName: local-path
    gateway:
      enabled: true
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: loki.local
          paths:
            - path: /
              pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: ""

