apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-storage
  namespace: wordpress
  labels:
    app: wordpress
    backup: "true"
  annotations:
    backup.velero.io/backup-volumes: "wordpress-storage"
    description: "WordPress application data and uploads"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

