apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db-secret
    namespace: wordpress
type: Opaque
stringData:
    MYSQL_DATABASE: ENC[AES256_GCM,data:C9oBGIyQwLy+,iv:RVE1qK1q1pntgGK1NPV7L6lc2+b73g9im51RDr+7fiY=,tag:r+hICs/7Fp/ROOkCWzE/WA==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:ij89ddMDFw7R,iv:HcxwEafvHN2XdXiDBNyylspYqjc8ZC91gVLnAn47L+o=,tag:FWs5x8oY6K3cJP6cIFK4/Q==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:b0gOF0UB7Mc8E8+h,iv:QE/HQ5J97UHNvyrUB5G9ouTjg4fYPtyUrPd+v4vldWc=,tag:S0OGitZMgDKCnjMOs+u2gg==,type:str]
sops:
    age:
        - recipient: age1qmghm4s7u0n5y0h6pn9jr9ljskwwetn4u6td7d9dv02regtzpy4sgctrqm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1T0xvRW42cVUvVlFkdW0x
            NFZuMUFzbmUvMmFrN1JtVkk0bGhDdjFCRERNCk9xVm5VbU1OWU9YVDByMFppRzdi
            N0hTZnhKQTEyejRPbUpjS2t6UDUrN3cKLS0tIGU1MFI5bXNKVDJHZDBsZVR4TkdK
            RXN1OHVad3didC80SmNGNTBWQkdBZmsK696kAqSmlkcQYujx5PT1vFExNO4UJr8W
            GrVNs+Hv88OKmApDsuka4ui+Ziv6V6X6OZCGATeX80hdlICDvdmJZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T16:26:15Z"
    mac: ENC[AES256_GCM,data:XgEsbbwUFm2q23upXqDI9Ind+5z1HKJUaBuZ6USVXr3R+JNQNHk3Tf3YxolzWvkYJKfrubxNBxtMseXE+YUTcKBbbZpNb+3gw2mo5C7rp/CbgCzfB36aHM4P80u+mpZzEMqmasnRAXceQ6/Vr2nmSwhl8VWEuRXTJMvUG2aqODE=,iv:m1Ip2wXLeITBWkQkAbqSzWMFGQdFXUmWhLLVCDxLA9k=,tag:U0buXVB5/boiLwpi3GyTPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
