apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
stringData:
  age.agekey: |
    # SOPS_AGE_KEY_FILE content goes here
    # Generate with: age-keygen -o age.agekey
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Decryption
metadata:
  name: sops-decrypt
  namespace: flux-system
spec:
  provider: sops
  secretRef:
    name: sops-age

