apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
stringData:
  age.agekey: |
    age1qmghm4s7u0n5y0h6pn9jr9ljskwwetn4u6td7d9dv02regtzpy4sgctrqm
    # The private key starts with: AGE-SECRET-KEY-1...
    # NOT the public key (age1...)
    AGE-SECRET-KEY-1YOUR_PRIVATE_KEY_HERE

