apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
stringData:
  age.agekey: |
    AGE-SECRET-KEY-1TW8W0G4ZZ0GDUGZ4DS0YY6WZYQG4JKMCJ869XKVQXGY4RR96S9UQ0UKRHW

